package dev.jentic.runtime.memory.llm;

import dev.jentic.core.llm.LLMMessage;
import dev.jentic.core.memory.llm.ContextWindowStrategy;
import dev.jentic.core.memory.llm.TokenEstimator;

import java.util.ArrayList;
import java.util.List;

/**
 * Summarization strategy - includes recent messages plus summary of old conversation.
 * 
 * <p><b>Algorithm:</b>
 * <ol>
 *   <li>Include most recent messages (last 10)</li>
 *   <li>If older messages exist, create summary</li>
 *   <li>Insert summary as system message</li>
 *   <li>Adjust token budget accordingly</li>
 * </ol>
 * 
 * <p><b>Note:</b> This is a placeholder implementation. The actual summarization
 * requires an LLM call, which will be implemented in the full {@code DefaultLLMMemoryManager}.
 * This version marks where the summary would go but doesn't generate it.
 * 
 * <p><b>Characteristics:</b>
 * <ul>
 *   <li><b>Pros:</b> Preserves overall context, continuous narrative</li>
 *   <li><b>Cons:</b> Requires LLM call for summarization, slower (~1-2s)</li>
 *   <li><b>Best For:</b> Very long conversations where context is critical</li>
 *   <li><b>Performance:</b> O(n) time + LLM call, O(n) space</li>
 *   <li><b>Requires LLM:</b> Yes (for full implementation)</li>
 *   <li><b>Overhead:</b> ~200 tokens for summary</li>
 * </ul>
 * 
 * <p><b>Example:</b>
 * <pre>{@code
 * ContextWindowStrategy strategy = new SummarizationStrategy();
 * 
 * List<LLMMessage> selected = strategy.selectMessages(
 *     allMessages,
 *     2000,  // Token budget
 *     estimator
 * );
 * 
 * // Or use singleton from factory
 * import static dev.jentic.runtime.memory.llm.ContextWindowStrategies.SUMMARIZED;
 * List<LLMMessage> selected = SUMMARIZED.selectMessages(allMessages, 2000, estimator);
 * }</pre>
 * 
 * <p><b>Full Implementation:</b>
 * <pre>{@code
 * // When LLMProvider is available, summarization will work like this:
 * LLMRequest summaryRequest = LLMRequest.builder(model)
 *     .systemMessage("Summarize the following conversation concisely")
 *     .messages(oldMessages)
 *     .maxTokens(200)
 *     .build();
 * 
 * LLMResponse summaryResponse = llmProvider.chat(summaryRequest).join();
 * String summary = summaryResponse.content();
 * }</pre>
 * 
 * <p><b>Thread Safety:</b> This class is stateless and thread-safe.
 * 
 * @since 0.6.0
 */
public class SummarizationStrategy implements ContextWindowStrategy {
    
    /**
     * Number of recent messages to keep unsummarized.
     */
    private static final int RECENT_MESSAGE_COUNT = 10;
    
    /**
     * Estimated token count for a typical summary.
     */
    private static final int ESTIMATED_SUMMARY_TOKENS = 200;
    
    /**
     * Create a new summarization strategy instance.
     */
    public SummarizationStrategy() {
        // Stateless - no initialization needed
    }
    
    @Override
    public List<LLMMessage> selectMessages(
        List<LLMMessage> allMessages,
        int maxTokens,
        TokenEstimator estimator
    ) {
        // Validate parameters
        if (allMessages == null) {
            throw new IllegalArgumentException("allMessages cannot be null");
        }
        if (maxTokens <= 0) {
            throw new IllegalArgumentException("maxTokens must be positive");
        }
        if (estimator == null) {
            throw new IllegalArgumentException("estimator cannot be null");
        }
        
        // Handle empty list
        if (allMessages.isEmpty()) {
            return List.of();
        }
        
        // If few messages, use fixed strategy (no summarization needed)
        if (allMessages.size() <= RECENT_MESSAGE_COUNT) {
            return new FixedWindowStrategy().selectMessages(allMessages, maxTokens, estimator);
        }
        
        // NOTE: This is a placeholder implementation
        // Full implementation would call LLM to generate actual summary
        List<LLMMessage> selected = new ArrayList<>();
        
        // Calculate how many old messages would be summarized
        int oldMessageCount = allMessages.size() - RECENT_MESSAGE_COUNT;
        
        // Placeholder for where summary would go
        // In full implementation, this would be actual LLM-generated summary
        String summaryPlaceholder = String.format(
            "[Summary of %d earlier messages would be generated by LLM here]",
            oldMessageCount
        );
        
        // Estimate tokens for summary (use placeholder for now)
        int summaryTokens = estimator.estimateTokens(summaryPlaceholder);
        int currentTokens = summaryTokens;
        
        // Add recent messages that fit in remaining budget
        int recentStart = Math.max(0, allMessages.size() - RECENT_MESSAGE_COUNT);
        for (int i = recentStart; i < allMessages.size(); i++) {
            LLMMessage msg = allMessages.get(i);
            int msgTokens = estimator.estimateTokens(msg);
            
            if (currentTokens + msgTokens <= maxTokens) {
                selected.add(msg);
                currentTokens += msgTokens;
            } else {
                // Budget exhausted, stop adding messages
                break;
            }
        }
        
        return selected;
    }
    
    @Override
    public String getName() {
        return "summarized";
    }
    
    @Override
    public boolean requiresLLM() {
        return true;  // Full implementation needs LLM for summarization
    }
    
    @Override
    public int getOverheadTokens() {
        return ESTIMATED_SUMMARY_TOKENS;
    }
    
    /**
     * Generate summary of old messages (to be implemented with LLMProvider).
     * 
     * <p>This method is for future implementation when {@code DefaultLLMMemoryManager}
     * integrates summarization. It will use an LLM to create a concise summary
     * of older messages.
     * 
     * @param oldMessages messages to summarize
     * @param llmProvider LLM provider for generating summary
     * @param model model to use for summarization
     * @return summary text
     */
    @SuppressWarnings("unused")
    private String generateSummary(
        List<LLMMessage> oldMessages,
        Object llmProvider,  // Will be LLMProvider when implemented
        String model
    ) {
        // TODO: Implement when LLMProvider integration is ready
        // For now, return placeholder
        return String.format("[Summary of %d messages]", oldMessages.size());
        
        /*
        // Future implementation:
        LLMRequest summaryRequest = LLMRequest.builder(model)
            .systemMessage("Summarize the following conversation concisely, " +
                          "preserving key facts and context.")
            .messages(oldMessages)
            .maxTokens(200)
            .temperature(0.3)  // Lower temp for consistent summaries
            .build();
        
        LLMResponse response = llmProvider.chat(summaryRequest).join();
        return response.content();
        */
    }
}
