package dev.jentic.runtime.behavior.orchestrator;

/**
 * Subtask generated by LLM decomposition.
 * 
 * @param workerName target worker name
 * @param task task description
 * @param priority execution priority (lower = higher priority)
 * @since 0.7.0
 */
public record SubTask(
    String workerName,
    String task,
    int priority
) {
    public SubTask(String workerName, String task) {
        this(workerName, task, 0);
    }
}
